# Udacity Deep Learning Nanodegree - Course Notes

- Author : Navneet Kumar
- Date : 1st June 2020

-------

<img src="Images/Deep_Learning.png" width="500" height="600">

## 1. Introductions

----

### 1.1 Welcome

----

- Number of uses around Machine Translation, Computer Vision
- Projects :
    - Predict Bike Rentals through Neural Networks
    - Detects Dogs in the picture
    - RNN - New Scripts for the TV Show
    - GAN - Human Faces
    - Re-inforcement Learning - Flying Simulators

### 1.5 Matrix Math and Numpy Refresher

---

Important Reminders About Matrix Multiplication
- The number of columns in the left matrix must equal the number of rows in the right matrix.
- The answer matrix always has the same number of rows as the left matrix and the same number of columns as the right matrix.
- Order matters. Multiplying A•B is not the same as multiplying B•A.
- Data in the left matrix should be arranged as rows., while data in the right matrix should be arranged as columns.

#### NumPy Matrix Multiplication

Element-wise Multiplication
- You saw some element-wise multiplication already. You accomplish that with the multiply function or the * operator. Just to revisit, it would look like this:

In [2]:
import numpy as np
m = np.array([[1,2,3],[4,5,6]])
m
# displays the following result:
# array([[1, 2, 3],
#        [4, 5, 6]])

n = m * 0.25
n
# displays the following result:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

#### Matrix Product
- To find the matrix product, you use NumPy's matmul function. If you have compatible shapes, then it's as simple as this:

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a.shape
# displays the following result:
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b.shape
# displays the following result:
# (4, 3)

c = np.matmul(a, b)
c
# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
print(c)
c.shape
# displays the following result:
# (2, 3)

[[ 70  80  90]
 [158 184 210]]


(2, 3)

#### Transpose

In [5]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m
# displays the following result:
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

m.T
# displays the following result:
# array([[ 1,  5,  9],
#        [ 2,  6, 10],
#        [ 3,  7, 11],
#        [ 4,  8, 12]])

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])